#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertinvoceSecond(invoceSecond instance);
    partial void UpdateinvoceSecond(invoceSecond instance);
    partial void DeleteinvoceSecond(invoceSecond instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WpfApp7.Properties.Settings.Default.testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<invoceSecond> invoceSeconds
		{
			get
			{
				return this.GetTable<invoceSecond>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.invoceSecond")]
	public partial class invoceSecond : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _DealNumber;
		
		private string _TIN;
		
		private string _BuyerBankName;
		
		private string _BuyerBankAccountNumber;
		
		private string _GoodDescription;
		
		private System.Nullable<int> _GoodAmount;
		
		private System.Nullable<int> _PricePerUnit;
		
		private System.Nullable<int> _Price;
		
		private string _DeliveryDate;
		
		private string _DealDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnDealNumberChanging(string value);
    partial void OnDealNumberChanged();
    partial void OnTINChanging(string value);
    partial void OnTINChanged();
    partial void OnBuyerBankNameChanging(string value);
    partial void OnBuyerBankNameChanged();
    partial void OnBuyerBankAccountNumberChanging(string value);
    partial void OnBuyerBankAccountNumberChanged();
    partial void OnGoodDescriptionChanging(string value);
    partial void OnGoodDescriptionChanged();
    partial void OnGoodAmountChanging(System.Nullable<int> value);
    partial void OnGoodAmountChanged();
    partial void OnPricePerUnitChanging(System.Nullable<int> value);
    partial void OnPricePerUnitChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    partial void OnDeliveryDateChanging(string value);
    partial void OnDeliveryDateChanged();
    partial void OnDealDateChanging(string value);
    partial void OnDealDateChanged();
    #endregion
		
		public invoceSecond()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealNumber", DbType="VarChar(50)")]
		public string DealNumber
		{
			get
			{
				return this._DealNumber;
			}
			set
			{
				if ((this._DealNumber != value))
				{
					this.OnDealNumberChanging(value);
					this.SendPropertyChanging();
					this._DealNumber = value;
					this.SendPropertyChanged("DealNumber");
					this.OnDealNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIN", DbType="VarChar(50)")]
		public string TIN
		{
			get
			{
				return this._TIN;
			}
			set
			{
				if ((this._TIN != value))
				{
					this.OnTINChanging(value);
					this.SendPropertyChanging();
					this._TIN = value;
					this.SendPropertyChanged("TIN");
					this.OnTINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerBankName", DbType="VarChar(50)")]
		public string BuyerBankName
		{
			get
			{
				return this._BuyerBankName;
			}
			set
			{
				if ((this._BuyerBankName != value))
				{
					this.OnBuyerBankNameChanging(value);
					this.SendPropertyChanging();
					this._BuyerBankName = value;
					this.SendPropertyChanged("BuyerBankName");
					this.OnBuyerBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerBankAccountNumber", DbType="VarChar(50)")]
		public string BuyerBankAccountNumber
		{
			get
			{
				return this._BuyerBankAccountNumber;
			}
			set
			{
				if ((this._BuyerBankAccountNumber != value))
				{
					this.OnBuyerBankAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._BuyerBankAccountNumber = value;
					this.SendPropertyChanged("BuyerBankAccountNumber");
					this.OnBuyerBankAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodDescription", DbType="VarChar(50)")]
		public string GoodDescription
		{
			get
			{
				return this._GoodDescription;
			}
			set
			{
				if ((this._GoodDescription != value))
				{
					this.OnGoodDescriptionChanging(value);
					this.SendPropertyChanging();
					this._GoodDescription = value;
					this.SendPropertyChanged("GoodDescription");
					this.OnGoodDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodAmount", DbType="Int")]
		public System.Nullable<int> GoodAmount
		{
			get
			{
				return this._GoodAmount;
			}
			set
			{
				if ((this._GoodAmount != value))
				{
					this.OnGoodAmountChanging(value);
					this.SendPropertyChanging();
					this._GoodAmount = value;
					this.SendPropertyChanged("GoodAmount");
					this.OnGoodAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricePerUnit", DbType="Int")]
		public System.Nullable<int> PricePerUnit
		{
			get
			{
				return this._PricePerUnit;
			}
			set
			{
				if ((this._PricePerUnit != value))
				{
					this.OnPricePerUnitChanging(value);
					this.SendPropertyChanging();
					this._PricePerUnit = value;
					this.SendPropertyChanged("PricePerUnit");
					this.OnPricePerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryDate", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string DeliveryDate
		{
			get
			{
				return this._DeliveryDate;
			}
			set
			{
				if ((this._DeliveryDate != value))
				{
					this.OnDeliveryDateChanging(value);
					this.SendPropertyChanging();
					this._DeliveryDate = value;
					this.SendPropertyChanged("DeliveryDate");
					this.OnDeliveryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealDate", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string DealDate
		{
			get
			{
				return this._DealDate;
			}
			set
			{
				if ((this._DealDate != value))
				{
					this.OnDealDateChanging(value);
					this.SendPropertyChanging();
					this._DealDate = value;
					this.SendPropertyChanged("DealDate");
					this.OnDealDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
